language: python

os:
  - linux

dist: trusty
sudo: enabled

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo add-apt-repository 'deb http://ftp.indexdata.dk/ubuntu trusty main'
  - sudo apt-get -qq update
  - sudo apt-get install -y yaz
  - yaz-marcdump -V

install: pip install -r requirements.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: pytest
