language: python

os:
  - linux

dist: trusty
sudo: enabled

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y yaz ; fi
  - yaz-marcdump -V

install: pip install -r requirements.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: pytest
